// Code generated by protoc-gen-go. DO NOT EDIT.
// source: velo_node.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VeloTxRequest struct {
	SignedVeloTxXdr      string   `protobuf:"bytes,1,opt,name=signedVeloTxXdr,proto3" json:"signedVeloTxXdr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VeloTxRequest) Reset()         { *m = VeloTxRequest{} }
func (m *VeloTxRequest) String() string { return proto.CompactTextString(m) }
func (*VeloTxRequest) ProtoMessage()    {}
func (*VeloTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{0}
}

func (m *VeloTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VeloTxRequest.Unmarshal(m, b)
}
func (m *VeloTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VeloTxRequest.Marshal(b, m, deterministic)
}
func (m *VeloTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VeloTxRequest.Merge(m, src)
}
func (m *VeloTxRequest) XXX_Size() int {
	return xxx_messageInfo_VeloTxRequest.Size(m)
}
func (m *VeloTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VeloTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VeloTxRequest proto.InternalMessageInfo

func (m *VeloTxRequest) GetSignedVeloTxXdr() string {
	if m != nil {
		return m.SignedVeloTxXdr
	}
	return ""
}

type VeloTxReply struct {
	SignedStellarTxXdr   string   `protobuf:"bytes,1,opt,name=signedStellarTxXdr,proto3" json:"signedStellarTxXdr,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VeloTxReply) Reset()         { *m = VeloTxReply{} }
func (m *VeloTxReply) String() string { return proto.CompactTextString(m) }
func (*VeloTxReply) ProtoMessage()    {}
func (*VeloTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{1}
}

func (m *VeloTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VeloTxReply.Unmarshal(m, b)
}
func (m *VeloTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VeloTxReply.Marshal(b, m, deterministic)
}
func (m *VeloTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VeloTxReply.Merge(m, src)
}
func (m *VeloTxReply) XXX_Size() int {
	return xxx_messageInfo_VeloTxReply.Size(m)
}
func (m *VeloTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VeloTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_VeloTxReply proto.InternalMessageInfo

func (m *VeloTxReply) GetSignedStellarTxXdr() string {
	if m != nil {
		return m.SignedStellarTxXdr
	}
	return ""
}

func (m *VeloTxReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetExchangeRateRequest struct {
	AssetCode            string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	Issuer               string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExchangeRateRequest) Reset()         { *m = GetExchangeRateRequest{} }
func (m *GetExchangeRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetExchangeRateRequest) ProtoMessage()    {}
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{2}
}

func (m *GetExchangeRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExchangeRateRequest.Unmarshal(m, b)
}
func (m *GetExchangeRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExchangeRateRequest.Marshal(b, m, deterministic)
}
func (m *GetExchangeRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExchangeRateRequest.Merge(m, src)
}
func (m *GetExchangeRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetExchangeRateRequest.Size(m)
}
func (m *GetExchangeRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExchangeRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExchangeRateRequest proto.InternalMessageInfo

func (m *GetExchangeRateRequest) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetExchangeRateRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

type GetExchangeRateReply struct {
	AssetCode              string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	Issuer                 string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	RedeemableCollateral   string   `protobuf:"bytes,3,opt,name=redeemableCollateral,proto3" json:"redeemableCollateral,omitempty"`
	RedeemablePricePerUnit string   `protobuf:"bytes,4,opt,name=redeemablePricePerUnit,proto3" json:"redeemablePricePerUnit,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetExchangeRateReply) Reset()         { *m = GetExchangeRateReply{} }
func (m *GetExchangeRateReply) String() string { return proto.CompactTextString(m) }
func (*GetExchangeRateReply) ProtoMessage()    {}
func (*GetExchangeRateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{3}
}

func (m *GetExchangeRateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExchangeRateReply.Unmarshal(m, b)
}
func (m *GetExchangeRateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExchangeRateReply.Marshal(b, m, deterministic)
}
func (m *GetExchangeRateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExchangeRateReply.Merge(m, src)
}
func (m *GetExchangeRateReply) XXX_Size() int {
	return xxx_messageInfo_GetExchangeRateReply.Size(m)
}
func (m *GetExchangeRateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExchangeRateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetExchangeRateReply proto.InternalMessageInfo

func (m *GetExchangeRateReply) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetExchangeRateReply) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *GetExchangeRateReply) GetRedeemableCollateral() string {
	if m != nil {
		return m.RedeemableCollateral
	}
	return ""
}

func (m *GetExchangeRateReply) GetRedeemablePricePerUnit() string {
	if m != nil {
		return m.RedeemablePricePerUnit
	}
	return ""
}

type GetCollateralHealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollateralHealthCheckRequest) Reset()         { *m = GetCollateralHealthCheckRequest{} }
func (m *GetCollateralHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollateralHealthCheckRequest) ProtoMessage()    {}
func (*GetCollateralHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{4}
}

func (m *GetCollateralHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetCollateralHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetCollateralHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollateralHealthCheckRequest.Merge(m, src)
}
func (m *GetCollateralHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Size(m)
}
func (m *GetCollateralHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollateralHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollateralHealthCheckRequest proto.InternalMessageInfo

type GetCollateralHealthCheckReply struct {
	AssetCode            string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	AssetIssuer          string   `protobuf:"bytes,2,opt,name=assetIssuer,proto3" json:"assetIssuer,omitempty"`
	RequiredAmount       string   `protobuf:"bytes,3,opt,name=requiredAmount,proto3" json:"requiredAmount,omitempty"`
	PoolAmount           string   `protobuf:"bytes,4,opt,name=poolAmount,proto3" json:"poolAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollateralHealthCheckReply) Reset()         { *m = GetCollateralHealthCheckReply{} }
func (m *GetCollateralHealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*GetCollateralHealthCheckReply) ProtoMessage()    {}
func (*GetCollateralHealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{5}
}

func (m *GetCollateralHealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Unmarshal(m, b)
}
func (m *GetCollateralHealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Marshal(b, m, deterministic)
}
func (m *GetCollateralHealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollateralHealthCheckReply.Merge(m, src)
}
func (m *GetCollateralHealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Size(m)
}
func (m *GetCollateralHealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollateralHealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollateralHealthCheckReply proto.InternalMessageInfo

func (m *GetCollateralHealthCheckReply) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetAssetIssuer() string {
	if m != nil {
		return m.AssetIssuer
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetRequiredAmount() string {
	if m != nil {
		return m.RequiredAmount
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetPoolAmount() string {
	if m != nil {
		return m.PoolAmount
	}
	return ""
}

func init() {
	proto.RegisterType((*VeloTxRequest)(nil), "grpc.VeloTxRequest")
	proto.RegisterType((*VeloTxReply)(nil), "grpc.VeloTxReply")
	proto.RegisterType((*GetExchangeRateRequest)(nil), "grpc.GetExchangeRateRequest")
	proto.RegisterType((*GetExchangeRateReply)(nil), "grpc.GetExchangeRateReply")
	proto.RegisterType((*GetCollateralHealthCheckRequest)(nil), "grpc.GetCollateralHealthCheckRequest")
	proto.RegisterType((*GetCollateralHealthCheckReply)(nil), "grpc.GetCollateralHealthCheckReply")
}

func init() { proto.RegisterFile("velo_node.proto", fileDescriptor_a824ed0044bf442b) }

var fileDescriptor_a824ed0044bf442b = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x5b, 0x44, 0xcb, 0xd0, 0x16, 0x75, 0x8b, 0x90, 0x65, 0xd1, 0x96, 0xba, 0x6a, 0xc5,
	0xc9, 0x07, 0x2a, 0x55, 0xcd, 0x31, 0x42, 0x11, 0xc9, 0x21, 0x08, 0x41, 0xbe, 0x6e, 0xd1, 0x62,
	0x8f, 0x6c, 0x2b, 0x6b, 0xaf, 0xd9, 0x5d, 0x47, 0xf0, 0x8b, 0xf2, 0x17, 0xf2, 0xe7, 0x22, 0x45,
	0xfe, 0x0a, 0x86, 0xe0, 0x20, 0xe5, 0x38, 0x6f, 0xde, 0xbc, 0x9d, 0xb7, 0xfb, 0x16, 0x5a, 0xb7,
	0xc8, 0xf8, 0x75, 0xc8, 0x1d, 0xb4, 0x22, 0xc1, 0x15, 0x27, 0x35, 0x57, 0x44, 0xb6, 0x79, 0x00,
	0x9f, 0x2e, 0x90, 0xf1, 0xb3, 0xe5, 0x14, 0x17, 0x31, 0x4a, 0x45, 0xfa, 0xd0, 0x92, 0xbe, 0x1b,
	0xa2, 0x93, 0xc1, 0x57, 0x8e, 0xd0, 0xb5, 0x9e, 0xd6, 0x6f, 0x4c, 0xb7, 0x61, 0xf3, 0x12, 0x9a,
	0xc5, 0x68, 0xc4, 0x56, 0xc4, 0x02, 0x92, 0x31, 0x66, 0x0a, 0x19, 0xa3, 0xa2, 0x3c, 0xbb, 0xa3,
	0x43, 0x74, 0x78, 0x1f, 0xa0, 0x94, 0xd4, 0x45, 0xfd, 0x6d, 0x4a, 0x2a, 0x4a, 0x73, 0x0c, 0x9d,
	0x11, 0xaa, 0xa3, 0xa5, 0xed, 0xd1, 0xd0, 0xc5, 0x29, 0x55, 0x58, 0x2c, 0xd7, 0x85, 0x06, 0x95,
	0x12, 0xd5, 0x90, 0x3b, 0x98, 0x4b, 0xaf, 0x01, 0xd2, 0x81, 0xba, 0x2f, 0x65, 0x8c, 0x22, 0x17,
	0xcc, 0x2b, 0xf3, 0x5e, 0x83, 0xf6, 0x33, 0xc1, 0x64, 0xe5, 0x57, 0xc9, 0x91, 0x01, 0xb4, 0x05,
	0x3a, 0x88, 0x01, 0x9d, 0x33, 0x1c, 0x72, 0xc6, 0xa8, 0x42, 0x41, 0x99, 0xfe, 0x2e, 0x65, 0xed,
	0xec, 0x91, 0x7f, 0xd0, 0x59, 0xe3, 0x13, 0xe1, 0xdb, 0x38, 0x41, 0x71, 0x1e, 0xfa, 0x4a, 0xaf,
	0xa5, 0x53, 0x15, 0x5d, 0xf3, 0x27, 0xfc, 0x18, 0x25, 0xeb, 0x14, 0x42, 0xc7, 0x48, 0x99, 0xf2,
	0x86, 0x1e, 0xda, 0x37, 0xf9, 0x9d, 0x98, 0x77, 0x1a, 0x7c, 0xab, 0xe6, 0xec, 0xb7, 0xd9, 0x83,
	0x66, 0x5a, 0x9c, 0x94, 0xbd, 0x96, 0x21, 0xf2, 0x07, 0x3e, 0x0b, 0x5c, 0xc4, 0xbe, 0x40, 0xe7,
	0x30, 0xe0, 0x71, 0xa8, 0x72, 0xab, 0x5b, 0x28, 0xf9, 0x0e, 0x10, 0x71, 0xce, 0x72, 0x4e, 0x66,
	0xac, 0x84, 0x0c, 0x1e, 0x34, 0xf8, 0x90, 0x24, 0x66, 0x9c, 0x1c, 0xfb, 0x1f, 0x3e, 0xce, 0xe2,
	0x79, 0xe0, 0xab, 0x2c, 0x43, 0xe4, 0xab, 0x95, 0xe4, 0xd1, 0xda, 0x08, 0xa3, 0xf1, 0x65, 0x13,
	0x8c, 0xd8, 0xca, 0x7c, 0x43, 0x4e, 0xa1, 0xb5, 0xf5, 0x9a, 0xa4, 0x9b, 0xf1, 0x76, 0xa7, 0xc6,
	0x30, 0x2a, 0xba, 0x99, 0x9c, 0x07, 0x7a, 0xd5, 0xf5, 0x91, 0xdf, 0x4f, 0x93, 0x2f, 0x3d, 0x81,
	0xf1, 0x6b, 0x1f, 0x2d, 0x3d, 0x69, 0x5e, 0x4f, 0x3f, 0xde, 0xdf, 0xc7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x7a, 0x1a, 0xff, 0x8b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VeloNodeClient is the client API for VeloNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VeloNodeClient interface {
	SubmitVeloTx(ctx context.Context, in *VeloTxRequest, opts ...grpc.CallOption) (*VeloTxReply, error)
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error)
	GetCollateralHealthCheck(ctx context.Context, in *GetCollateralHealthCheckRequest, opts ...grpc.CallOption) (*GetCollateralHealthCheckReply, error)
}

type veloNodeClient struct {
	cc *grpc.ClientConn
}

func NewVeloNodeClient(cc *grpc.ClientConn) VeloNodeClient {
	return &veloNodeClient{cc}
}

func (c *veloNodeClient) SubmitVeloTx(ctx context.Context, in *VeloTxRequest, opts ...grpc.CallOption) (*VeloTxReply, error) {
	out := new(VeloTxReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/SubmitVeloTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veloNodeClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error) {
	out := new(GetExchangeRateReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/GetExchangeRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veloNodeClient) GetCollateralHealthCheck(ctx context.Context, in *GetCollateralHealthCheckRequest, opts ...grpc.CallOption) (*GetCollateralHealthCheckReply, error) {
	out := new(GetCollateralHealthCheckReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/GetCollateralHealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VeloNodeServer is the server API for VeloNode service.
type VeloNodeServer interface {
	SubmitVeloTx(context.Context, *VeloTxRequest) (*VeloTxReply, error)
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateReply, error)
	GetCollateralHealthCheck(context.Context, *GetCollateralHealthCheckRequest) (*GetCollateralHealthCheckReply, error)
}

// UnimplementedVeloNodeServer can be embedded to have forward compatible implementations.
type UnimplementedVeloNodeServer struct {
}

func (*UnimplementedVeloNodeServer) SubmitVeloTx(ctx context.Context, req *VeloTxRequest) (*VeloTxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVeloTx not implemented")
}
func (*UnimplementedVeloNodeServer) GetExchangeRate(ctx context.Context, req *GetExchangeRateRequest) (*GetExchangeRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (*UnimplementedVeloNodeServer) GetCollateralHealthCheck(ctx context.Context, req *GetCollateralHealthCheckRequest) (*GetCollateralHealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollateralHealthCheck not implemented")
}

func RegisterVeloNodeServer(s *grpc.Server, srv VeloNodeServer) {
	s.RegisterService(&_VeloNode_serviceDesc, srv)
}

func _VeloNode_SubmitVeloTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VeloTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).SubmitVeloTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/SubmitVeloTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).SubmitVeloTx(ctx, req.(*VeloTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeloNode_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/GetExchangeRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeloNode_GetCollateralHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollateralHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).GetCollateralHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/GetCollateralHealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).GetCollateralHealthCheck(ctx, req.(*GetCollateralHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VeloNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.VeloNode",
	HandlerType: (*VeloNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVeloTx",
			Handler:    _VeloNode_SubmitVeloTx_Handler,
		},
		{
			MethodName: "GetExchangeRate",
			Handler:    _VeloNode_GetExchangeRate_Handler,
		},
		{
			MethodName: "GetCollateralHealthCheck",
			Handler:    _VeloNode_GetCollateralHealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "velo_node.proto",
}
