// Code generated by protoc-gen-go. DO NOT EDIT.
// source: velo_node.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VeloTxRequest struct {
	SignedVeloTxXdr      string   `protobuf:"bytes,1,opt,name=signedVeloTxXdr,proto3" json:"signedVeloTxXdr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VeloTxRequest) Reset()         { *m = VeloTxRequest{} }
func (m *VeloTxRequest) String() string { return proto.CompactTextString(m) }
func (*VeloTxRequest) ProtoMessage()    {}
func (*VeloTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{0}
}

func (m *VeloTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VeloTxRequest.Unmarshal(m, b)
}
func (m *VeloTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VeloTxRequest.Marshal(b, m, deterministic)
}
func (m *VeloTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VeloTxRequest.Merge(m, src)
}
func (m *VeloTxRequest) XXX_Size() int {
	return xxx_messageInfo_VeloTxRequest.Size(m)
}
func (m *VeloTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VeloTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VeloTxRequest proto.InternalMessageInfo

func (m *VeloTxRequest) GetSignedVeloTxXdr() string {
	if m != nil {
		return m.SignedVeloTxXdr
	}
	return ""
}

type VeloTxReply struct {
	SignedStellarTxXdr         string                      `protobuf:"bytes,1,opt,name=signedStellarTxXdr,proto3" json:"signedStellarTxXdr,omitempty"`
	Message                    string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WhitelistOpResponse        *WhitelistOpResponse        `protobuf:"bytes,3,opt,name=whitelistOpResponse,proto3" json:"whitelistOpResponse,omitempty"`
	SetupCreditOpResponse      *SetupCreditOpResponse      `protobuf:"bytes,4,opt,name=setupCreditOpResponse,proto3" json:"setupCreditOpResponse,omitempty"`
	PriceUpdateOpResponse      *PriceUpdateOpResponse      `protobuf:"bytes,5,opt,name=priceUpdateOpResponse,proto3" json:"priceUpdateOpResponse,omitempty"`
	MintCreditOpResponse       *MintCreditOpResponse       `protobuf:"bytes,6,opt,name=mintCreditOpResponse,proto3" json:"mintCreditOpResponse,omitempty"`
	RedeemCreditOpResponse     *RedeemCreditOpResponse     `protobuf:"bytes,7,opt,name=redeemCreditOpResponse,proto3" json:"redeemCreditOpResponse,omitempty"`
	RebalanceReserveOpResponse *RebalanceReserveOpResponse `protobuf:"bytes,8,opt,name=rebalanceReserveOpResponse,proto3" json:"rebalanceReserveOpResponse,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *VeloTxReply) Reset()         { *m = VeloTxReply{} }
func (m *VeloTxReply) String() string { return proto.CompactTextString(m) }
func (*VeloTxReply) ProtoMessage()    {}
func (*VeloTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{1}
}

func (m *VeloTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VeloTxReply.Unmarshal(m, b)
}
func (m *VeloTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VeloTxReply.Marshal(b, m, deterministic)
}
func (m *VeloTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VeloTxReply.Merge(m, src)
}
func (m *VeloTxReply) XXX_Size() int {
	return xxx_messageInfo_VeloTxReply.Size(m)
}
func (m *VeloTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VeloTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_VeloTxReply proto.InternalMessageInfo

func (m *VeloTxReply) GetSignedStellarTxXdr() string {
	if m != nil {
		return m.SignedStellarTxXdr
	}
	return ""
}

func (m *VeloTxReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VeloTxReply) GetWhitelistOpResponse() *WhitelistOpResponse {
	if m != nil {
		return m.WhitelistOpResponse
	}
	return nil
}

func (m *VeloTxReply) GetSetupCreditOpResponse() *SetupCreditOpResponse {
	if m != nil {
		return m.SetupCreditOpResponse
	}
	return nil
}

func (m *VeloTxReply) GetPriceUpdateOpResponse() *PriceUpdateOpResponse {
	if m != nil {
		return m.PriceUpdateOpResponse
	}
	return nil
}

func (m *VeloTxReply) GetMintCreditOpResponse() *MintCreditOpResponse {
	if m != nil {
		return m.MintCreditOpResponse
	}
	return nil
}

func (m *VeloTxReply) GetRedeemCreditOpResponse() *RedeemCreditOpResponse {
	if m != nil {
		return m.RedeemCreditOpResponse
	}
	return nil
}

func (m *VeloTxReply) GetRebalanceReserveOpResponse() *RebalanceReserveOpResponse {
	if m != nil {
		return m.RebalanceReserveOpResponse
	}
	return nil
}

type WhitelistOpResponse struct {
	Address                   string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role                      string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Currency                  string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TrustedPartnerMetaAddress string   `protobuf:"bytes,4,opt,name=trustedPartnerMetaAddress,proto3" json:"trustedPartnerMetaAddress,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *WhitelistOpResponse) Reset()         { *m = WhitelistOpResponse{} }
func (m *WhitelistOpResponse) String() string { return proto.CompactTextString(m) }
func (*WhitelistOpResponse) ProtoMessage()    {}
func (*WhitelistOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{2}
}

func (m *WhitelistOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistOpResponse.Unmarshal(m, b)
}
func (m *WhitelistOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistOpResponse.Marshal(b, m, deterministic)
}
func (m *WhitelistOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistOpResponse.Merge(m, src)
}
func (m *WhitelistOpResponse) XXX_Size() int {
	return xxx_messageInfo_WhitelistOpResponse.Size(m)
}
func (m *WhitelistOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistOpResponse proto.InternalMessageInfo

func (m *WhitelistOpResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WhitelistOpResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *WhitelistOpResponse) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *WhitelistOpResponse) GetTrustedPartnerMetaAddress() string {
	if m != nil {
		return m.TrustedPartnerMetaAddress
	}
	return ""
}

type SetupCreditOpResponse struct {
	AssetIssuer          string   `protobuf:"bytes,1,opt,name=assetIssuer,proto3" json:"assetIssuer,omitempty"`
	AssetDistributor     string   `protobuf:"bytes,2,opt,name=assetDistributor,proto3" json:"assetDistributor,omitempty"`
	AssetCode            string   `protobuf:"bytes,3,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	PeggedValue          string   `protobuf:"bytes,4,opt,name=peggedValue,proto3" json:"peggedValue,omitempty"`
	PeggedCurrency       string   `protobuf:"bytes,5,opt,name=peggedCurrency,proto3" json:"peggedCurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupCreditOpResponse) Reset()         { *m = SetupCreditOpResponse{} }
func (m *SetupCreditOpResponse) String() string { return proto.CompactTextString(m) }
func (*SetupCreditOpResponse) ProtoMessage()    {}
func (*SetupCreditOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{3}
}

func (m *SetupCreditOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupCreditOpResponse.Unmarshal(m, b)
}
func (m *SetupCreditOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupCreditOpResponse.Marshal(b, m, deterministic)
}
func (m *SetupCreditOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupCreditOpResponse.Merge(m, src)
}
func (m *SetupCreditOpResponse) XXX_Size() int {
	return xxx_messageInfo_SetupCreditOpResponse.Size(m)
}
func (m *SetupCreditOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupCreditOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupCreditOpResponse proto.InternalMessageInfo

func (m *SetupCreditOpResponse) GetAssetIssuer() string {
	if m != nil {
		return m.AssetIssuer
	}
	return ""
}

func (m *SetupCreditOpResponse) GetAssetDistributor() string {
	if m != nil {
		return m.AssetDistributor
	}
	return ""
}

func (m *SetupCreditOpResponse) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *SetupCreditOpResponse) GetPeggedValue() string {
	if m != nil {
		return m.PeggedValue
	}
	return ""
}

func (m *SetupCreditOpResponse) GetPeggedCurrency() string {
	if m != nil {
		return m.PeggedCurrency
	}
	return ""
}

type PriceUpdateOpResponse struct {
	Asset                       string   `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	Currency                    string   `protobuf:"bytes,2,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PriceInCurrencyPerAssetUnit string   `protobuf:"bytes,3,opt,name=PriceInCurrencyPerAssetUnit,proto3" json:"PriceInCurrencyPerAssetUnit,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *PriceUpdateOpResponse) Reset()         { *m = PriceUpdateOpResponse{} }
func (m *PriceUpdateOpResponse) String() string { return proto.CompactTextString(m) }
func (*PriceUpdateOpResponse) ProtoMessage()    {}
func (*PriceUpdateOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{4}
}

func (m *PriceUpdateOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceUpdateOpResponse.Unmarshal(m, b)
}
func (m *PriceUpdateOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceUpdateOpResponse.Marshal(b, m, deterministic)
}
func (m *PriceUpdateOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceUpdateOpResponse.Merge(m, src)
}
func (m *PriceUpdateOpResponse) XXX_Size() int {
	return xxx_messageInfo_PriceUpdateOpResponse.Size(m)
}
func (m *PriceUpdateOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceUpdateOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceUpdateOpResponse proto.InternalMessageInfo

func (m *PriceUpdateOpResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *PriceUpdateOpResponse) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PriceUpdateOpResponse) GetPriceInCurrencyPerAssetUnit() string {
	if m != nil {
		return m.PriceInCurrencyPerAssetUnit
	}
	return ""
}

type MintCreditOpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintCreditOpResponse) Reset()         { *m = MintCreditOpResponse{} }
func (m *MintCreditOpResponse) String() string { return proto.CompactTextString(m) }
func (*MintCreditOpResponse) ProtoMessage()    {}
func (*MintCreditOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{5}
}

func (m *MintCreditOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCreditOpResponse.Unmarshal(m, b)
}
func (m *MintCreditOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCreditOpResponse.Marshal(b, m, deterministic)
}
func (m *MintCreditOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCreditOpResponse.Merge(m, src)
}
func (m *MintCreditOpResponse) XXX_Size() int {
	return xxx_messageInfo_MintCreditOpResponse.Size(m)
}
func (m *MintCreditOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCreditOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MintCreditOpResponse proto.InternalMessageInfo

type RedeemCreditOpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemCreditOpResponse) Reset()         { *m = RedeemCreditOpResponse{} }
func (m *RedeemCreditOpResponse) String() string { return proto.CompactTextString(m) }
func (*RedeemCreditOpResponse) ProtoMessage()    {}
func (*RedeemCreditOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{6}
}

func (m *RedeemCreditOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemCreditOpResponse.Unmarshal(m, b)
}
func (m *RedeemCreditOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemCreditOpResponse.Marshal(b, m, deterministic)
}
func (m *RedeemCreditOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemCreditOpResponse.Merge(m, src)
}
func (m *RedeemCreditOpResponse) XXX_Size() int {
	return xxx_messageInfo_RedeemCreditOpResponse.Size(m)
}
func (m *RedeemCreditOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemCreditOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemCreditOpResponse proto.InternalMessageInfo

type RebalanceReserveOpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebalanceReserveOpResponse) Reset()         { *m = RebalanceReserveOpResponse{} }
func (m *RebalanceReserveOpResponse) String() string { return proto.CompactTextString(m) }
func (*RebalanceReserveOpResponse) ProtoMessage()    {}
func (*RebalanceReserveOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{7}
}

func (m *RebalanceReserveOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebalanceReserveOpResponse.Unmarshal(m, b)
}
func (m *RebalanceReserveOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebalanceReserveOpResponse.Marshal(b, m, deterministic)
}
func (m *RebalanceReserveOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebalanceReserveOpResponse.Merge(m, src)
}
func (m *RebalanceReserveOpResponse) XXX_Size() int {
	return xxx_messageInfo_RebalanceReserveOpResponse.Size(m)
}
func (m *RebalanceReserveOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RebalanceReserveOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RebalanceReserveOpResponse proto.InternalMessageInfo

type GetExchangeRateRequest struct {
	AssetCode            string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	Issuer               string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExchangeRateRequest) Reset()         { *m = GetExchangeRateRequest{} }
func (m *GetExchangeRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetExchangeRateRequest) ProtoMessage()    {}
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{8}
}

func (m *GetExchangeRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExchangeRateRequest.Unmarshal(m, b)
}
func (m *GetExchangeRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExchangeRateRequest.Marshal(b, m, deterministic)
}
func (m *GetExchangeRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExchangeRateRequest.Merge(m, src)
}
func (m *GetExchangeRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetExchangeRateRequest.Size(m)
}
func (m *GetExchangeRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExchangeRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExchangeRateRequest proto.InternalMessageInfo

func (m *GetExchangeRateRequest) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetExchangeRateRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

type GetExchangeRateReply struct {
	AssetCode              string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	Issuer                 string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	RedeemableCollateral   string   `protobuf:"bytes,3,opt,name=redeemableCollateral,proto3" json:"redeemableCollateral,omitempty"`
	RedeemablePricePerUnit string   `protobuf:"bytes,4,opt,name=redeemablePricePerUnit,proto3" json:"redeemablePricePerUnit,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetExchangeRateReply) Reset()         { *m = GetExchangeRateReply{} }
func (m *GetExchangeRateReply) String() string { return proto.CompactTextString(m) }
func (*GetExchangeRateReply) ProtoMessage()    {}
func (*GetExchangeRateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{9}
}

func (m *GetExchangeRateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExchangeRateReply.Unmarshal(m, b)
}
func (m *GetExchangeRateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExchangeRateReply.Marshal(b, m, deterministic)
}
func (m *GetExchangeRateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExchangeRateReply.Merge(m, src)
}
func (m *GetExchangeRateReply) XXX_Size() int {
	return xxx_messageInfo_GetExchangeRateReply.Size(m)
}
func (m *GetExchangeRateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExchangeRateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetExchangeRateReply proto.InternalMessageInfo

func (m *GetExchangeRateReply) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetExchangeRateReply) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *GetExchangeRateReply) GetRedeemableCollateral() string {
	if m != nil {
		return m.RedeemableCollateral
	}
	return ""
}

func (m *GetExchangeRateReply) GetRedeemablePricePerUnit() string {
	if m != nil {
		return m.RedeemablePricePerUnit
	}
	return ""
}

type GetCollateralHealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollateralHealthCheckRequest) Reset()         { *m = GetCollateralHealthCheckRequest{} }
func (m *GetCollateralHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollateralHealthCheckRequest) ProtoMessage()    {}
func (*GetCollateralHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{10}
}

func (m *GetCollateralHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetCollateralHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetCollateralHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollateralHealthCheckRequest.Merge(m, src)
}
func (m *GetCollateralHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollateralHealthCheckRequest.Size(m)
}
func (m *GetCollateralHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollateralHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollateralHealthCheckRequest proto.InternalMessageInfo

type GetCollateralHealthCheckReply struct {
	AssetCode            string   `protobuf:"bytes,1,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	AssetIssuer          string   `protobuf:"bytes,2,opt,name=assetIssuer,proto3" json:"assetIssuer,omitempty"`
	RequiredAmount       string   `protobuf:"bytes,3,opt,name=requiredAmount,proto3" json:"requiredAmount,omitempty"`
	PoolAmount           string   `protobuf:"bytes,4,opt,name=poolAmount,proto3" json:"poolAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollateralHealthCheckReply) Reset()         { *m = GetCollateralHealthCheckReply{} }
func (m *GetCollateralHealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*GetCollateralHealthCheckReply) ProtoMessage()    {}
func (*GetCollateralHealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a824ed0044bf442b, []int{11}
}

func (m *GetCollateralHealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Unmarshal(m, b)
}
func (m *GetCollateralHealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Marshal(b, m, deterministic)
}
func (m *GetCollateralHealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollateralHealthCheckReply.Merge(m, src)
}
func (m *GetCollateralHealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_GetCollateralHealthCheckReply.Size(m)
}
func (m *GetCollateralHealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollateralHealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollateralHealthCheckReply proto.InternalMessageInfo

func (m *GetCollateralHealthCheckReply) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetAssetIssuer() string {
	if m != nil {
		return m.AssetIssuer
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetRequiredAmount() string {
	if m != nil {
		return m.RequiredAmount
	}
	return ""
}

func (m *GetCollateralHealthCheckReply) GetPoolAmount() string {
	if m != nil {
		return m.PoolAmount
	}
	return ""
}

func init() {
	proto.RegisterType((*VeloTxRequest)(nil), "grpc.VeloTxRequest")
	proto.RegisterType((*VeloTxReply)(nil), "grpc.VeloTxReply")
	proto.RegisterType((*WhitelistOpResponse)(nil), "grpc.WhitelistOpResponse")
	proto.RegisterType((*SetupCreditOpResponse)(nil), "grpc.SetupCreditOpResponse")
	proto.RegisterType((*PriceUpdateOpResponse)(nil), "grpc.PriceUpdateOpResponse")
	proto.RegisterType((*MintCreditOpResponse)(nil), "grpc.MintCreditOpResponse")
	proto.RegisterType((*RedeemCreditOpResponse)(nil), "grpc.RedeemCreditOpResponse")
	proto.RegisterType((*RebalanceReserveOpResponse)(nil), "grpc.RebalanceReserveOpResponse")
	proto.RegisterType((*GetExchangeRateRequest)(nil), "grpc.GetExchangeRateRequest")
	proto.RegisterType((*GetExchangeRateReply)(nil), "grpc.GetExchangeRateReply")
	proto.RegisterType((*GetCollateralHealthCheckRequest)(nil), "grpc.GetCollateralHealthCheckRequest")
	proto.RegisterType((*GetCollateralHealthCheckReply)(nil), "grpc.GetCollateralHealthCheckReply")
}

func init() { proto.RegisterFile("velo_node.proto", fileDescriptor_a824ed0044bf442b) }

var fileDescriptor_a824ed0044bf442b = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x3e, 0xee, 0x49, 0xff, 0xa6, 0xe7, 0xb4, 0xe7, 0x4c, 0xd3, 0x28, 0x75, 0x0b, 0x04, 0x23,
	0xaa, 0x8a, 0x8b, 0x5c, 0x14, 0x09, 0x81, 0xc4, 0x05, 0x55, 0x40, 0xa5, 0x42, 0x2d, 0xc1, 0xfd,
	0x81, 0x3b, 0xd8, 0xc4, 0xa3, 0xc4, 0x62, 0x63, 0xbb, 0xbb, 0xeb, 0xd2, 0x3e, 0x03, 0xcf, 0xc0,
	0x35, 0xaf, 0xc0, 0x4b, 0x70, 0xc3, 0xfb, 0x20, 0x21, 0xef, 0xda, 0xc1, 0x4d, 0xd6, 0xad, 0xc4,
	0x9d, 0xe7, 0xf3, 0x37, 0xdf, 0xce, 0xcc, 0x7e, 0xbb, 0x0b, 0x2b, 0xe7, 0xc4, 0xe3, 0xf7, 0x51,
	0x1c, 0x50, 0x3b, 0x11, 0xb1, 0x8a, 0xb1, 0x36, 0x10, 0x49, 0xdf, 0x7b, 0x02, 0xff, 0x9e, 0x12,
	0x8f, 0x8f, 0x2f, 0x7c, 0x3a, 0x4b, 0x49, 0x2a, 0xdc, 0x86, 0x15, 0x19, 0x0e, 0x22, 0x0a, 0x0c,
	0xfc, 0x2e, 0x10, 0x4d, 0xa7, 0xe5, 0x6c, 0x2f, 0xfa, 0x93, 0xb0, 0xf7, 0xa3, 0x06, 0x4b, 0x45,
	0x6e, 0xc2, 0x2f, 0xb1, 0x0d, 0x68, 0x28, 0x47, 0x8a, 0x38, 0x67, 0xa2, 0x9c, 0x6c, 0xf9, 0x83,
	0x4d, 0x98, 0x1f, 0x91, 0x94, 0x6c, 0x40, 0xcd, 0x19, 0x4d, 0x2a, 0x42, 0x7c, 0x05, 0xab, 0x9f,
	0x86, 0xa1, 0x22, 0x1e, 0x4a, 0xf5, 0x3a, 0xf1, 0x49, 0x26, 0x71, 0x24, 0xa9, 0xf9, 0x77, 0xcb,
	0xd9, 0x5e, 0xda, 0x59, 0x6f, 0x67, 0x85, 0xb7, 0xdf, 0x4e, 0x13, 0x7c, 0x5b, 0x16, 0xbe, 0x81,
	0x35, 0x49, 0x2a, 0x4d, 0x3a, 0x82, 0x82, 0xb0, 0x2c, 0x57, 0xd3, 0x72, 0x1b, 0x46, 0xee, 0xc8,
	0x46, 0xf1, 0xed, 0x99, 0x99, 0x64, 0x22, 0xc2, 0x3e, 0x9d, 0x24, 0x01, 0x53, 0x54, 0x92, 0x9c,
	0x2d, 0x4b, 0x76, 0x6d, 0x14, 0xdf, 0x9e, 0x89, 0x87, 0x50, 0x1f, 0x85, 0x91, 0x9a, 0x2a, 0x72,
	0x4e, 0x2b, 0xba, 0x46, 0xf1, 0xc0, 0xc2, 0xf0, 0xad, 0x79, 0x78, 0x0c, 0x0d, 0x41, 0x01, 0xd1,
	0x68, 0x4a, 0x71, 0x5e, 0x2b, 0x6e, 0x1a, 0x45, 0xdf, 0xca, 0xf1, 0x2b, 0x72, 0xf1, 0x03, 0xb8,
	0x82, 0x7a, 0x8c, 0xb3, 0xa8, 0x4f, 0x3e, 0x49, 0x12, 0xe7, 0xe5, 0xee, 0x17, 0xb4, 0x72, 0xab,
	0x50, 0xae, 0xe2, 0xf9, 0xd7, 0x68, 0x78, 0x5f, 0x1c, 0x58, 0xb5, 0x6c, 0x6d, 0x66, 0x16, 0x16,
	0x04, 0x82, 0xa4, 0xcc, 0x1d, 0x55, 0x84, 0x88, 0x50, 0x13, 0x31, 0x2f, 0x3c, 0xa4, 0xbf, 0xd1,
	0x85, 0x85, 0x7e, 0x2a, 0x04, 0x45, 0xfd, 0x4b, 0xed, 0x9a, 0x45, 0x7f, 0x1c, 0xe3, 0x53, 0x58,
	0x57, 0x22, 0x95, 0x8a, 0x82, 0x2e, 0x13, 0x2a, 0x22, 0x71, 0x40, 0x8a, 0xed, 0xe6, 0xda, 0x35,
	0x4d, 0xae, 0x26, 0x78, 0xdf, 0x1d, 0x58, 0xb3, 0x7a, 0x05, 0x5b, 0xb0, 0xc4, 0xa4, 0x24, 0xb5,
	0x2f, 0x65, 0x4a, 0x85, 0xef, 0xcb, 0x10, 0x3e, 0x80, 0xff, 0x74, 0xf8, 0x3c, 0x94, 0x4a, 0x84,
	0xbd, 0x54, 0xc5, 0x22, 0xaf, 0x7a, 0x0a, 0xc7, 0x4d, 0x58, 0xd4, 0x58, 0x27, 0x0e, 0x28, 0x6f,
	0xe1, 0x37, 0x90, 0xad, 0x95, 0xd0, 0x60, 0x40, 0xc1, 0x29, 0xe3, 0x29, 0xe5, 0x55, 0x97, 0x21,
	0xdc, 0x82, 0x65, 0x13, 0x76, 0x8a, 0x39, 0xcc, 0x6a, 0xd2, 0x04, 0xea, 0x7d, 0x76, 0x60, 0xcd,
	0x6a, 0x54, 0xac, 0xc3, 0xec, 0x6e, 0xb6, 0x60, 0xde, 0x89, 0x09, 0xb2, 0xc9, 0x8e, 0x15, 0x4d,
	0xed, 0xe3, 0x18, 0x9f, 0xc1, 0x86, 0x96, 0xda, 0x8f, 0x0a, 0xa8, 0x4b, 0x42, 0xa7, 0x9d, 0x44,
	0xa1, 0xca, 0xbb, 0xb8, 0x8e, 0xe2, 0x35, 0xa0, 0x6e, 0xf3, 0xb8, 0xd7, 0x84, 0x86, 0xdd, 0xa9,
	0xde, 0x26, 0xb8, 0xd5, 0x4e, 0xf3, 0x0e, 0xa1, 0xb1, 0x47, 0xea, 0xc5, 0x45, 0x7f, 0xc8, 0xa2,
	0x01, 0xf9, 0x4c, 0x51, 0x71, 0xcd, 0x5d, 0x99, 0xaf, 0x33, 0x39, 0xdf, 0x06, 0xcc, 0x85, 0x66,
	0x1b, 0x4d, 0x8f, 0x79, 0xe4, 0x7d, 0x73, 0xa0, 0x3e, 0x25, 0x98, 0xdd, 0x7d, 0x7f, 0x24, 0x87,
	0x3b, 0x50, 0x37, 0x07, 0x8d, 0xf5, 0x38, 0x75, 0x62, 0xce, 0x99, 0x22, 0xc1, 0x78, 0x3e, 0x29,
	0xeb, 0x3f, 0x7c, 0x54, 0x1c, 0xec, 0x0c, 0xd7, 0xb3, 0xec, 0x92, 0xd0, 0xf3, 0x35, 0x2e, 0xa8,
	0xf8, 0xeb, 0xdd, 0x85, 0x3b, 0x7b, 0x59, 0x39, 0x85, 0xd0, 0x4b, 0x62, 0x5c, 0x0d, 0x3b, 0x43,
	0xea, 0x7f, 0xcc, 0x67, 0xe2, 0x7d, 0x75, 0xe0, 0x56, 0x35, 0xe7, 0xe6, 0x36, 0x27, 0x4e, 0xc0,
	0xcc, 0xf4, 0x09, 0xd8, 0x82, 0x65, 0x41, 0x67, 0x69, 0x28, 0x28, 0xd8, 0x1d, 0xc5, 0x69, 0x54,
	0x98, 0x62, 0x02, 0xc5, 0xdb, 0x00, 0x49, 0x1c, 0xf3, 0x9c, 0x63, 0x1a, 0x2b, 0x21, 0x3b, 0x3f,
	0x1d, 0x58, 0xc8, 0x9e, 0x9e, 0xc3, 0x6c, 0xd9, 0xc7, 0xf0, 0xcf, 0x51, 0xda, 0x1b, 0x85, 0xca,
	0x3c, 0x46, 0xb8, 0x6a, 0x2e, 0xa0, 0x2b, 0xcf, 0x9a, 0xfb, 0xff, 0x55, 0x30, 0xe1, 0x97, 0xde,
	0x5f, 0x78, 0x00, 0x2b, 0x13, 0xbb, 0x89, 0xf9, 0xbd, 0x68, 0x77, 0x8d, 0xeb, 0x56, 0xfc, 0x35,
	0x72, 0x43, 0x68, 0x56, 0x8d, 0x0f, 0xef, 0x8f, 0x33, 0xaf, 0xdb, 0x02, 0xf7, 0xde, 0x4d, 0x34,
	0xbd, 0x52, 0x6f, 0x4e, 0x3f, 0xe1, 0x0f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xba, 0x0f, 0x9a,
	0xad, 0xd5, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VeloNodeClient is the client API for VeloNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VeloNodeClient interface {
	SubmitVeloTx(ctx context.Context, in *VeloTxRequest, opts ...grpc.CallOption) (*VeloTxReply, error)
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error)
	GetCollateralHealthCheck(ctx context.Context, in *GetCollateralHealthCheckRequest, opts ...grpc.CallOption) (*GetCollateralHealthCheckReply, error)
}

type veloNodeClient struct {
	cc *grpc.ClientConn
}

func NewVeloNodeClient(cc *grpc.ClientConn) VeloNodeClient {
	return &veloNodeClient{cc}
}

func (c *veloNodeClient) SubmitVeloTx(ctx context.Context, in *VeloTxRequest, opts ...grpc.CallOption) (*VeloTxReply, error) {
	out := new(VeloTxReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/SubmitVeloTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veloNodeClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error) {
	out := new(GetExchangeRateReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/GetExchangeRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veloNodeClient) GetCollateralHealthCheck(ctx context.Context, in *GetCollateralHealthCheckRequest, opts ...grpc.CallOption) (*GetCollateralHealthCheckReply, error) {
	out := new(GetCollateralHealthCheckReply)
	err := c.cc.Invoke(ctx, "/grpc.VeloNode/GetCollateralHealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VeloNodeServer is the server API for VeloNode service.
type VeloNodeServer interface {
	SubmitVeloTx(context.Context, *VeloTxRequest) (*VeloTxReply, error)
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateReply, error)
	GetCollateralHealthCheck(context.Context, *GetCollateralHealthCheckRequest) (*GetCollateralHealthCheckReply, error)
}

// UnimplementedVeloNodeServer can be embedded to have forward compatible implementations.
type UnimplementedVeloNodeServer struct {
}

func (*UnimplementedVeloNodeServer) SubmitVeloTx(ctx context.Context, req *VeloTxRequest) (*VeloTxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVeloTx not implemented")
}
func (*UnimplementedVeloNodeServer) GetExchangeRate(ctx context.Context, req *GetExchangeRateRequest) (*GetExchangeRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (*UnimplementedVeloNodeServer) GetCollateralHealthCheck(ctx context.Context, req *GetCollateralHealthCheckRequest) (*GetCollateralHealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollateralHealthCheck not implemented")
}

func RegisterVeloNodeServer(s *grpc.Server, srv VeloNodeServer) {
	s.RegisterService(&_VeloNode_serviceDesc, srv)
}

func _VeloNode_SubmitVeloTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VeloTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).SubmitVeloTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/SubmitVeloTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).SubmitVeloTx(ctx, req.(*VeloTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeloNode_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/GetExchangeRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeloNode_GetCollateralHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollateralHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeloNodeServer).GetCollateralHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.VeloNode/GetCollateralHealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeloNodeServer).GetCollateralHealthCheck(ctx, req.(*GetCollateralHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VeloNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.VeloNode",
	HandlerType: (*VeloNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitVeloTx",
			Handler:    _VeloNode_SubmitVeloTx_Handler,
		},
		{
			MethodName: "GetExchangeRate",
			Handler:    _VeloNode_GetExchangeRate_Handler,
		},
		{
			MethodName: "GetCollateralHealthCheck",
			Handler:    _VeloNode_GetCollateralHealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "velo_node.proto",
}
