// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/layers/usecases/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	txnbuild "gitlab.com/velo-labs/cen/libs/txnbuild"
	entities "gitlab.com/velo-labs/cen/node/app/entities"
	errors "gitlab.com/velo-labs/cen/node/app/errors"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SetupCredit mocks base method
func (m *MockUseCase) SetupCredit(ctx context.Context, veloTx *txnbuild.VeloTx) (*string, errors.NodeError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupCredit", ctx, veloTx)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(errors.NodeError)
	return ret0, ret1
}

// SetupCredit indicates an expected call of SetupCredit
func (mr *MockUseCaseMockRecorder) SetupCredit(ctx, veloTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupCredit", reflect.TypeOf((*MockUseCase)(nil).SetupCredit), ctx, veloTx)
}

// CreateWhitelist mocks base method
func (m *MockUseCase) CreateWhitelist(ctx context.Context, veloTx *txnbuild.VeloTx) (*string, errors.NodeError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWhitelist", ctx, veloTx)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(errors.NodeError)
	return ret0, ret1
}

// CreateWhitelist indicates an expected call of CreateWhitelist
func (mr *MockUseCaseMockRecorder) CreateWhitelist(ctx, veloTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWhitelist", reflect.TypeOf((*MockUseCase)(nil).CreateWhitelist), ctx, veloTx)
}

// UpdatePrice mocks base method
func (m *MockUseCase) UpdatePrice(ctx context.Context, veloTx *txnbuild.VeloTx) (*string, errors.NodeError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrice", ctx, veloTx)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(errors.NodeError)
	return ret0, ret1
}

// UpdatePrice indicates an expected call of UpdatePrice
func (mr *MockUseCaseMockRecorder) UpdatePrice(ctx, veloTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrice", reflect.TypeOf((*MockUseCase)(nil).UpdatePrice), ctx, veloTx)
}

// MintCredit mocks base method
func (m *MockUseCase) MintCredit(ctx context.Context, veloTx *txnbuild.VeloTx) (*entities.MintCreditOutput, errors.NodeError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintCredit", ctx, veloTx)
	ret0, _ := ret[0].(*entities.MintCreditOutput)
	ret1, _ := ret[1].(errors.NodeError)
	return ret0, ret1
}

// MintCredit indicates an expected call of MintCredit
func (mr *MockUseCaseMockRecorder) MintCredit(ctx, veloTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintCredit", reflect.TypeOf((*MockUseCase)(nil).MintCredit), ctx, veloTx)
}

// RedeemCredit mocks base method
func (m *MockUseCase) RedeemCredit(ctx context.Context, veloTx *txnbuild.VeloTx) (*entities.RedeemCreditOutput, errors.NodeError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemCredit", ctx, veloTx)
	ret0, _ := ret[0].(*entities.RedeemCreditOutput)
	ret1, _ := ret[1].(errors.NodeError)
	return ret0, ret1
}

// RedeemCredit indicates an expected call of RedeemCredit
func (mr *MockUseCaseMockRecorder) RedeemCredit(ctx, veloTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemCredit", reflect.TypeOf((*MockUseCase)(nil).RedeemCredit), ctx, veloTx)
}
