// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/layers/usecases/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	xdr "gitlab.com/velo-labs/cen/libs/xdr"
	entities "gitlab.com/velo-labs/cen/node/app/entities"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SetupAccount mocks base method
func (m *MockUseCase) SetupAccount(issuerCreationTx, peggedValue, peggedCurrency, assetName string) (*entities.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupAccount", issuerCreationTx, peggedValue, peggedCurrency, assetName)
	ret0, _ := ret[0].(*entities.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupAccount indicates an expected call of SetupAccount
func (mr *MockUseCaseMockRecorder) SetupAccount(issuerCreationTx, peggedValue, peggedCurrency, assetName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupAccount", reflect.TypeOf((*MockUseCase)(nil).SetupAccount), issuerCreationTx, peggedValue, peggedCurrency, assetName)
}

// CreateWhiteList mocks base method
func (m *MockUseCase) CreateWhiteList(ctx context.Context, veloTxEnvelope *xdr.VeloTxEnvelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWhiteList", ctx, veloTxEnvelope)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWhiteList indicates an expected call of CreateWhiteList
func (mr *MockUseCaseMockRecorder) CreateWhiteList(ctx, veloTxEnvelope interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWhiteList", reflect.TypeOf((*MockUseCase)(nil).CreateWhiteList), ctx, veloTxEnvelope)
}
