// Code generated by MockGen. DO NOT EDIT.
// Source: ./friendbot/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFreeLumens mocks base method
func (m *MockRepository) GetFreeLumens(stellarAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeLumens", stellarAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFreeLumens indicates an expected call of GetFreeLumens
func (mr *MockRepositoryMockRecorder) GetFreeLumens(stellarAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeLumens", reflect.TypeOf((*MockRepository)(nil).GetFreeLumens), stellarAddress)
}
