// Code generated by MockGen. DO NOT EDIT.
// Source: ./layers/repositories/stellar/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	horizon "github.com/stellar/go/protocols/horizon"
	reflect "reflect"
)

// MockStellarRepo is a mock of Repository interface
type MockStellarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStellarRepoMockRecorder
}

// MockStellarRepoMockRecorder is the mock recorder for MockStellarRepo
type MockStellarRepoMockRecorder struct {
	mock *MockStellarRepo
}

// NewMockStellarRepo creates a new mock instance
func NewMockStellarRepo(ctrl *gomock.Controller) *MockStellarRepo {
	mock := &MockStellarRepo{ctrl: ctrl}
	mock.recorder = &MockStellarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStellarRepo) EXPECT() *MockStellarRepoMockRecorder {
	return m.recorder
}

// GetFreeLumens mocks base method
func (m *MockStellarRepo) GetFreeLumens(stellarAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeLumens", stellarAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetFreeLumens indicates an expected call of GetFreeLumens
func (mr *MockStellarRepoMockRecorder) GetFreeLumens(stellarAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeLumens", reflect.TypeOf((*MockStellarRepo)(nil).GetFreeLumens), stellarAddress)
}

// GetStellarAccount mocks base method
func (m *MockStellarRepo) GetStellarAccount(stellarAddress string) (*horizon.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStellarAccount", stellarAddress)
	ret0, _ := ret[0].(*horizon.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStellarAccount indicates an expected call of GetStellarAccount
func (mr *MockStellarRepoMockRecorder) GetStellarAccount(stellarAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStellarAccount", reflect.TypeOf((*MockStellarRepo)(nil).GetStellarAccount), stellarAddress)
}
