// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/config/interface.go

// Package mockutils is a generated GoMock package.
package mockutils

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockConfiguration is a mock of Configuration interface
type MockConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationMockRecorder
}

// MockConfigurationMockRecorder is the mock recorder for MockConfiguration
type MockConfigurationMockRecorder struct {
	mock *MockConfiguration
}

// NewMockConfiguration creates a new mock instance
func NewMockConfiguration(ctrl *gomock.Controller) *MockConfiguration {
	mock := &MockConfiguration{ctrl: ctrl}
	mock.recorder = &MockConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfiguration) EXPECT() *MockConfigurationMockRecorder {
	return m.recorder
}

// GetDefaultAccount mocks base method
func (m *MockConfiguration) GetDefaultAccount() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAccount")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDefaultAccount indicates an expected call of GetDefaultAccount
func (mr *MockConfigurationMockRecorder) GetDefaultAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAccount", reflect.TypeOf((*MockConfiguration)(nil).GetDefaultAccount))
}

// SetDefaultAccount mocks base method
func (m *MockConfiguration) SetDefaultAccount(account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultAccount", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultAccount indicates an expected call of SetDefaultAccount
func (mr *MockConfigurationMockRecorder) SetDefaultAccount(account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultAccount", reflect.TypeOf((*MockConfiguration)(nil).SetDefaultAccount), account)
}
