// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils/console/interface.go

// Package mockutils is a generated GoMock package.
package mockutils

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPrompt is a mock of Prompt interface
type MockPrompt struct {
	ctrl     *gomock.Controller
	recorder *MockPromptMockRecorder
}

// MockPromptMockRecorder is the mock recorder for MockPrompt
type MockPromptMockRecorder struct {
	mock *MockPrompt
}

// NewMockPrompt creates a new mock instance
func NewMockPrompt(ctrl *gomock.Controller) *MockPrompt {
	mock := &MockPrompt{ctrl: ctrl}
	mock.recorder = &MockPromptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrompt) EXPECT() *MockPromptMockRecorder {
	return m.recorder
}

// RequestPassphrase mocks base method
func (m *MockPrompt) RequestPassphrase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPassphrase")
	ret0, _ := ret[0].(string)
	return ret0
}

// RequestPassphrase indicates an expected call of RequestPassphrase
func (mr *MockPromptMockRecorder) RequestPassphrase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPassphrase", reflect.TypeOf((*MockPrompt)(nil).RequestPassphrase))
}
